services:
  angie:
    image: docker.angie.software/angie:minimal
    container_name: xray-angie
    restart: unless-stopped
    network_mode: host
    volumes:
      - angie-data:/var/lib/angie
      - ./angie.conf:/etc/angie/angie.conf:ro
      - ./mask:/var/www/html:ro

volumes:
  angie-data:
    driver: local
