FROM python:3.11-slim

WORKDIR /app

COPY panel.py /app/panel.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "panel.py"]
